import { ArrowDown, ArrowRight, ArrowUp, CheckCircle, Circle, CircleOff, HelpCircle, Timer } from "lucide-react";
import { z } from "zod";

const taskSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: z.string(),
  label: z.string(),
  priority: z.string(),
});

export type Task = z.infer<typeof taskSchema>;

const tasksData = [
  {
    id: "TASK-8782",
    title: "Não é possível comprimir o programa sem quantificar o pixel SSD de código aberto!",
    status: "em-andamento",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-7878",
    title: "Tente calcular o feed EXE, talvez ele indexe o pixel multibyte!",
    status: "backlog",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-7839",
    title: "Precisamos contornar a placa TCP neural!",
    status: "a-fazer",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-5562",
    title: "A interface SAS está fora, contorne o pixel de código aberto para podermos fazer backup da largura de banda PNG!",
    status: "backlog",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-8686",
    title: "Vou analisar o protocolo SSL sem fio, isso deve dirigir o painel da API!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-1280",
    title: "Use o painel TLS digital, depois você poderá transmitir o sistema háptico!",
    status: "concluido",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-7262",
    title: "A aplicação UTF8 está fora, analise a largura de banda neural para podermos fazer backup do firewall PNG!",
    status: "concluido",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-1138",
    title: "Gerar o driver não vai fazer nada, precisamos quantificar a largura de banda SMTP 1080p!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-7184",
    title: "Precisamos programar o pixel THX do back-end!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-5160",
    title: "Calcular o barramento não vai fazer nada, precisamos navegar o protocolo JSON do back-end!",
    status: "em-andamento",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-5618",
    title: "Gerar o driver não vai fazer nada, precisamos indexar a aplicação SSL online!",
    status: "concluido",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-6699",
    title: "Vou transmitir o capacitor JBOD sem fio, isso deve dirigir o feed do SSD!",
    status: "backlog",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-2858",
    title: "Precisamos sobrescrever o barramento UDP online!",
    status: "backlog",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-9864",
    title: "Vou reiniciar o painel FTP 1080p, isso deve matrizar o disco rígido HEX!",
    status: "concluido",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-8404",
    title: "Precisamos gerar o alarme HEX virtual!",
    status: "em-andamento",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-5365",
    title: "Fazer backup do pixel não vai fazer nada, precisamos transmitir o array IB primário!",
    status: "em-andamento",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-1780",
    title: "O feed CSS está fora, indexe o transmissor bluetooth para podermos comprimir o protocolo CLI!",
    status: "a-fazer",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-6938",
    title: "Use a aplicação SCSI redundante, depois você poderá invadir o alarme óptico!",
    status: "a-fazer",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-9885",
    title: "Precisamos comprimir o driver VGA auxiliar!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-3216",
    title: "Transmitir o transmissor não vai fazer nada, precisamos comprimir o sensor HDD virtual!",
    status: "backlog",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-9285",
    title: "O monitor IP está fora, copie o alarme háptico para podermos gerar o transmissor HTTP!",
    status: "a-fazer",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-1024",
    title: "Sobrescrever o microchip não vai fazer nada, precisamos transmitir o transmissor OCR digital!",
    status: "em-andamento",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-7068",
    title: "Não é possível gerar o capacitor sem indexar o pixel HEX sem fio!",
    status: "cancelado",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-6502",
    title: "Navegar o microchip não vai fazer nada, precisamos contornar o barramento SQL do back-end!",
    status: "a-fazer",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-5326",
    title: "Precisamos invadir o transmissor UTF8 redundante!",
    status: "a-fazer",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-6274",
    title: "Use o circuito PCI virtual, depois você poderá analisar o alarme bluetooth!",
    status: "cancelado",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-1571",
    title: "Vou inserir o circuito DRAM neural, isso deve protocolar a interface SMTP!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-9518",
    title: "Comprimir a interface não vai fazer nada, precisamos comprimir a matriz SDD online!",
    status: "cancelado",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-5581",
    title: "Vou sintetizar o pixel COM digital, isso deve transmitir o protocolo UTF8!",
    status: "backlog",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-2197",
    title: "Analisar o feed não vai fazer nada, precisamos copiar o barramento DRAM bluetooth!",
    status: "a-fazer",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-8484",
    title: "Precisamos analisar o firewall UDP de estado sólido!",
    status: "em-andamento",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-9892",
    title: "Se fizermos backup da aplicação, podemos acessar a aplicação UDP através do capacitor THX multibyte!",
    status: "concluido",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-9616",
    title: "Precisamos sintetizar o pixel ASCII multiplataforma!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-9744",
    title: "Use a placa IP do back-end, depois você poderá inserir o disco rígido de estado sólido!",
    status: "concluido",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-1376",
    title: "Gerar o alarme não vai fazer nada, precisamos gerar o capacitor IP móvel!",
    status: "backlog",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-7382",
    title: "Se fizermos backup do firewall, podemos acessar o alarme RAM através do pixel UTF8 primário!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-2290",
    title: "Vou comprimir o painel JSON virtual, isso deve aplicar o barramento UTF8!",
    status: "cancelado",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-1533",
    title: "Não é possível inserir o firewall sem sobrescrever o firewall TCP sem fio!",
    status: "concluido",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-4920",
    title: "Contornar o disco rígido não vai fazer nada, precisamos inserir o programa JSON bluetooth!",
    status: "em-andamento",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-5168",
    title: "Se sintetizarmos o barramento, podemos acessar o painel IP através do array TLS virtual!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-7103",
    title: "Precisamos analisar a largura de banda EXE multibyte!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-4314",
    title: "Se comprimirmos o programa, podemos acessar o alarme XML através da matriz COM multibyte!",
    status: "em-andamento",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-3415",
    title: "Use a aplicação XML multiplataforma, depois você poderá quantificar o feed de estado sólido!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-8339",
    title: "Tente calcular a interface DNS, talvez ela insira o capacitor bluetooth!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-6995",
    title: "Tente invadir a largura de banda XSS, talvez ela sobrescreva a matriz bluetooth!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-8053",
    title: "Se conectarmos o programa, podemos acessar a matriz UTF8 através do protocolo UDP digital!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-4336",
    title: "Se sintetizarmos o microchip, podemos acessar o sensor SAS através do programa UDP óptico!",
    status: "a-fazer",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-8790",
    title: "Vou fazer backup do alarme COM óptico, isso deve alarmar o capacitor RSS!",
    status: "concluido",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-8980",
    title: "Tente navegar o transmissor SQL, talvez ele faça backup do firewall virtual!",
    status: "cancelado",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-7342",
    title: "Use a placa CLI neural, depois você poderá analisar a porta online!",
    status: "backlog",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-5608",
    title: "Vou invadir o programa SSL háptico, isso deve barrar o transmissor UDP!",
    status: "cancelado",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-1606",
    title: "Vou gerar o firewall PNG bluetooth, isso deve pixelar o driver SSL!",
    status: "concluido",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-7872",
    title: "Transmitir o circuito não vai fazer nada, precisamos reiniciar o monitor RSS 1080p!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-4167",
    title: "Use o circuito SMS multiplataforma, depois você poderá sintetizar o feed óptico!",
    status: "cancelado",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-9581",
    title: "Não é possível indexar a porta sem invadir o monitor XSS multiplataforma!",
    status: "backlog",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-8806",
    title: "Precisamos contornar o painel SSL do back-end!",
    status: "concluido",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-6542",
    title: "Tente quantificar o firewall RSS, talvez ele quantifique o sistema de código aberto!",
    status: "concluido",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-6806",
    title: "O protocolo VGA está fora, reinicie a matriz do back-end para podermos analisar o painel CSS!",
    status: "cancelado",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-9549",
    title: "Não é possível contornar o barramento sem conectar o barramento JBOD neural!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-1075",
    title: "Fazer backup do driver não vai fazer nada, precisamos analisar o pixel RAM redundante!",
    status: "concluido",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-1427",
    title: "Use o circuito PCI auxiliar, depois você poderá calcular a interface multiplataforma!",
    status: "concluido",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-1907",
    title: "Invadir o circuito não vai fazer nada, precisamos fazer backup do sistema DRAM online!",
    status: "a-fazer",
    label: "documentacao",
    priority: "alta",
  },
  {
    id: "TASK-4309",
    title: "Se gerarmos o sistema, podemos acessar o sensor TCP através do pixel GB óptico!",
    status: "backlog",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-3973",
    title: "Vou analisar o array ADP do back-end, isso deve largura-banda a largura de banda RSS!",
    status: "a-fazer",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-7962",
    title: "Use o programa RAM sem fio, depois você poderá invadir o feed multiplataforma!",
    status: "cancelado",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-3360",
    title: "Não é possível quantificar o programa sem sintetizar a interface OCR neural!",
    status: "concluido",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-9887",
    title: "Use o sensor ASCII auxiliar, depois você poderá conectar a porta de estado sólido!",
    status: "backlog",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-3649",
    title: "Vou inserir o sistema USB virtual, isso deve circuitar o monitor DNS!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-3586",
    title: "Se quantificarmos o circuito, podemos acessar o feed CLI através do disco rígido SMS móvel!",
    status: "em-andamento",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-5150",
    title: "Vou invadir a porta XSS sem fio, isso deve transmitir a interface IP!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "media",
  },
  {
    id: "TASK-3652",
    title: "A interface SQL está fora, sobrescreva o barramento óptico para podermos programar a interface ASCII!",
    status: "backlog",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-6884",
    title: "Use o circuito PCI digital, depois você poderá sintetizar o microchip multibyte!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-1591",
    title: "Precisamos conectar o driver XSS móvel!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-3802",
    title: "Tente sobrescrever o protocolo ASCII, talvez ele analise a matriz virtual!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-7253",
    title: "Programar o capacitor não vai fazer nada, precisamos contornar o disco rígido IB neural!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-9739",
    title: "Precisamos invadir o barramento HDD multibyte!",
    status: "concluido",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-4424",
    title: "Tente invadir o alarme HEX, talvez ele conecte o pixel óptico!",
    status: "em-andamento",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-3922",
    title: "Não é possível fazer backup do capacitor sem gerar o programa PCI sem fio!",
    status: "backlog",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-4921",
    title: "Vou indexar o feed IP de código aberto, isso deve sistematizar a aplicação GB!",
    status: "cancelado",
    label: "bug",
    priority: "baixa",
  },
  {
    id: "TASK-5814",
    title: "Precisamos calcular o feed AGP 1080p!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-2645",
    title: "Sintetizar o sistema não vai fazer nada, precisamos navegar o firewall HDD multibyte!",
    status: "a-fazer",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-4535",
    title: "Tente copiar o circuito JSON, talvez ele conecte o feed sem fio!",
    status: "em-andamento",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-4463",
    title: "Precisamos copiar o monitor AGP de estado sólido!",
    status: "concluido",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-9745",
    title: "Se conectarmos o protocolo, podemos acessar o sistema GB através do microchip PCI bluetooth!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-2080",
    title: "Se inserirmos o barramento, podemos acessar a matriz RAM através da placa RAM auxiliar!",
    status: "a-fazer",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-3838",
    title: "Vou contornar a aplicação TCP online, isso deve painelar o sistema AGP!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-1340",
    title: "Precisamos navegar o circuito PNG virtual!",
    status: "a-fazer",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-6665",
    title: "Se analisarmos o monitor, podemos acessar o disco rígido SSD através do alarme AGP multiplataforma!",
    status: "cancelado",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-7585",
    title: "Se calcularmos o disco rígido, podemos acessar o programa SSL através do microchip CSS multibyte!",
    status: "backlog",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-6319",
    title: "Precisamos copiar o programa SCSI multibyte!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-4369",
    title: "Tente inserir o barramento SCSI, talvez ele gere o pixel 1080p!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-9035",
    title: "Precisamos sobrescrever o array PNG de estado sólido!",
    status: "cancelado",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-3970",
    title: "Não é possível indexar o transmissor sem quantificar a placa ASCII háptica!",
    status: "a-fazer",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-4473",
    title: "Não é possível contornar o protocolo sem sobrescrever o programa RSS neural!",
    status: "a-fazer",
    label: "documentacao",
    priority: "baixa",
  },
  {
    id: "TASK-4136",
    title: "Não é possível invadir o disco rígido sem invadir o programa JSON primário!",
    status: "cancelado",
    label: "bug",
    priority: "media",
  },
  {
    id: "TASK-3939",
    title: "Use o firewall SQL do back-end, depois você poderá conectar o disco rígido neural!",
    status: "concluido",
    label: "funcionalidade",
    priority: "baixa",
  },
  {
    id: "TASK-2007",
    title: "Vou inserir o protocolo USB do back-end, isso deve largura-banda o sistema PCI!",
    status: "backlog",
    label: "bug",
    priority: "alta",
  },
  {
    id: "TASK-7516",
    title: "Use o programa SQL primário, depois você poderá gerar o transmissor auxiliar!",
    status: "concluido",
    label: "documentacao",
    priority: "media",
  },
  {
    id: "TASK-6906",
    title: "Tente fazer backup do sistema DRAM, talvez ele reinicie o transmissor online!",
    status: "concluido",
    label: "funcionalidade",
    priority: "alta",
  },
  {
    id: "TASK-5207",
    title: "A interface SMS está fora, copie o barramento bluetooth para podermos quantificar a placa VGA!",
    status: "em-andamento",
    label: "bug",
    priority: "baixa",
  },
];

export const tasks = z.array(taskSchema).parse(tasksData);

export const labels = [
  {
    value: "bug",
    label: "Bug",
  },
  {
    value: "funcionalidade",
    label: "Funcionalidade",
  },
  {
    value: "documentacao",
    label: "Documentação",
  },
];

export const statuses = [
  {
    value: "backlog",
    label: "Backlog",
    icon: HelpCircle,
  },
  {
    value: "a-fazer",
    label: "A Fazer",
    icon: Circle,
  },
  {
    value: "em-andamento",
    label: "Em Andamento",
    icon: Timer,
  },
  {
    value: "concluido",
    label: "Concluído",
    icon: CheckCircle,
  },
  {
    value: "cancelado",
    label: "Cancelado",
    icon: CircleOff,
  },
];

export const priorities = [
  {
    label: "Baixa",
    value: "baixa",
    icon: ArrowDown,
  },
  {
    label: "Média",
    value: "media",
    icon: ArrowRight,
  },
  {
    label: "Alta",
    value: "alta",
    icon: ArrowUp,
  },
];
