import type { LucideIcon } from "lucide-react";
import { Clock3, Inbox, Mail, MessageCircle, Phone, Send, Star, User } from "lucide-react";

export type Conversation = {
  id: number;
  group: "Fixadas" | "Hoje" | "Ontem";
  name: string;
  subject: string;
  preview: string;
  time: string;
  isUnread: boolean;
  isOnline: boolean;
  unreadCount: number;
  contact: Contact;
  messages: Message[];
};

export type Message = {
  id: number;
  align: "start" | "end";
  text: string;
  time: string;
  reaction?: string;
};

export type Contact = {
  name: string;
  role: string;
  company: string;
  email: string;
  phone: string;
  website: string;
  location: string;
  timezone: string;
  status: string;
  qualifiedAt: string;
  tags: string[];
};

export type NavItem = {
  id: string;
  title: string;
  label?: string;
  icon: LucideIcon;
  isActive: boolean;
};

export const navItems: NavItem[] = [
  { id: "inbox", title: "Caixa de Entrada", label: "24", icon: Inbox, isActive: true },
  { id: "mentions", title: "Menções", label: "3", icon: Mail, isActive: false },
  { id: "snoozed", title: "Adiadas", icon: Clock3, isActive: false },
  { id: "sent", title: "Enviadas", icon: Send, isActive: false },
  { id: "all", title: "Todas as conversas", icon: MessageCircle, isActive: false },
  { id: "unassigned", title: "Não atribuídas", label: "7", icon: User, isActive: false },
];

export const channelItems: NavItem[] = [
  { id: "email", title: "E-mail", label: "18", icon: Mail, isActive: false },
  { id: "chat", title: "Chat", label: "5", icon: MessageCircle, isActive: false },
  { id: "whatsapp", title: "WhatsApp", label: "1", icon: Phone, isActive: false },
  { id: "instagram", title: "Instagram", label: "0", icon: Phone, isActive: false },
  { id: "facebook", title: "Facebook", label: "0", icon: Phone, isActive: false },
  { id: "phone", title: "Telefone", label: "0", icon: Phone, isActive: false },
];

export const viewItems: NavItem[] = [
  { id: "vip", title: "Clientes VIP", label: "8", icon: Star, isActive: false },
  { id: "orders", title: "Pedidos e Devoluções", label: "6", icon: Inbox, isActive: false },
  { id: "feedback", title: "Feedback do Produto", label: "2", icon: MessageCircle, isActive: false },
];

export const conversations: Conversation[] = [
  // Fixadas
  {
    id: 1,
    group: "Fixadas",
    name: "Olivia Rhye",
    subject: "Pipeline de deploy falhando no staging desde o último deploy",
    preview: "Estamos vendo erros 502 após a última build. O rollback não ajudou.",
    time: "Agora mesmo",
    isUnread: true,
    isOnline: true,
    unreadCount: 4,
    contact: {
      name: "Olivia Rhye",
      role: "Engenheira Sênior de DevOps",
      company: "Railway Systems Inc.",
      email: "olivia.rhye@weblabs.studio",
      phone: "+1 (415) 555-0123",
      website: "railway.co",
      location: "San Francisco, CA, EUA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      qualifiedAt: "5 de mar. de 2026",
      tags: ["DevOps", "Enterprise", "P0"],
    },
    messages: [
      {
        id: 101,
        align: "start",
        text: "Estamos vendo erros 502 no staging logo após a última build. Fazemos rollback, mas os health checks ainda estão vermelhos.",
        time: "10 min atrás",
      },
      {
        id: 102,
        align: "end",
        text: "Obrigado, Olivia. Estou verificando os logs de deploy e a configuração do gateway upstream agora.",
        time: "8 min atrás",
      },
      {
        id: 103,
        align: "start",
        text: "A parte estranha é que o tráfego da API parece normal, mas o container web está falhando nos readiness probes.",
        time: "5 min atrás",
      },
      {
        id: 104,
        align: "end",
        text: "Encontrei uma incompatibilidade nas variáveis de ambiente do staging. Estou aplicando a correção e confirmarei quando os probes se recuperarem.",
        time: "3 min atrás",
        reaction: "\u{1F44D}",
      },
      {
        id: 105,
        align: "start",
        text: "Ótimo. Mantenha-me informado, isso está bloqueando nossa passagem de QA.",
        time: "1 min atrás",
        reaction: "\u{1F440}",
      },
    ],
  },
  {
    id: 2,
    group: "Fixadas",
    name: "Phoenix Baker",
    subject: "Reembolso para pedido #8823 — cobrança duplicada",
    preview: "Fui cobrado duas vezes no dia 3. Alguém pode verificar isso e reverter a duplicata?",
    time: "5m",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Phoenix Baker",
      role: "Líder de Operações",
      company: "Meridian Retail Group",
      email: "phoenix.baker@weblabs.studio",
      phone: "+1 (312) 555-0184",
      website: "meridianretail.com",
      location: "Chicago, IL, EUA",
      timezone: "CDT (UTC-5)",
      status: "Cliente",
      qualifiedAt: "18 de jan. de 2026",
      tags: ["Cobrança", "Enterprise"],
    },
    messages: [
      {
        id: 201,
        align: "start",
        text: "Fui cobrado duas vezes pelo pedido #8823. Um pagamento foi compensado no dia 3 e a duplicata foi postada esta manhã.",
        time: "5 min atrás",
      },
      {
        id: 202,
        align: "end",
        text: "Obrigado por sinalizar, Phoenix. Consigo ver ambas as transações e estou verificando qual foi vinculada à fatura.",
        time: "4 min atrás",
      },
      {
        id: 203,
        align: "start",
        text: "Por favor, reverta a duplicata se possível. Nossa equipe financeira está encerrando a semana hoje.",
        time: "3 min atrás",
      },
      {
        id: 204,
        align: "end",
        text: "A duplicata foi uma nova tentativa do método de pagamento antigo. Iniciei o reembolso e enviei o recibo para seu e-mail de cobrança.",
        time: "2 min atrás",
        reaction: "\u{1F44D}",
      },
      {
        id: 205,
        align: "start",
        text: "Perfeito, obrigado. Vou informar a equipe financeira para esperar.",
        time: "1 min atrás",
        reaction: "\u2705",
      },
    ],
  },
  {
    id: 3,
    group: "Fixadas",
    name: "Lana Steiner",
    subject: "Acesso ao painel de analytics — problema de permissões",
    preview: "Estou recebendo erro 403 desde a atualização de cargo ontem. Já tentei limpar o cache.",
    time: "8m",
    isUnread: true,
    isOnline: false,
    unreadCount: 2,
    contact: {
      name: "Lana Steiner",
      role: "Líder de Plataforma de Dados",
      company: "Monsoon Analytics",
      email: "lana.steiner@acme.inc",
      phone: "+91 98765 43210",
      website: "monsoonanalytics.in",
      location: "Bengaluru, Índia",
      timezone: "IST (UTC+5:30)",
      status: "Qualificado",
      qualifiedAt: "2 de abr. de 2026",
      tags: ["IAM", "Enterprise", "Alto Valor"],
    },
    messages: [
      {
        id: 301,
        align: "start",
        text: "Estou recebendo erro 403 no painel de analytics desde a atualização de cargo de ontem. Limpar o cache não mudou nada.",
        time: "8 min atrás",
      },
      {
        id: 302,
        align: "end",
        text: "Obrigado, Lana. Vou comparar seu novo cargo com o conjunto de permissões do painel.",
        time: "7 min atrás",
      },
      {
        id: 303,
        align: "start",
        text: "Ainda tenho acesso às exportações, apenas não às visualizações do painel. Outros administradores da minha equipe conseguem abri-las.",
        time: "5 min atrás",
      },
      {
        id: 304,
        align: "end",
        text: "Parece que a permissão de Visualizador de Analytics foi removida do seu cargo personalizado. A reanexei para seu workspace.",
        time: "3 min atrás",
        reaction: "\u{1F64C}",
      },
      {
        id: 305,
        align: "start",
        text: "Isso resolveu. Obrigado pela ajuda rápida.",
        time: "1 min atrás",
        reaction: "\u{1F389}",
      },
    ],
  },
  // Hoje
  {
    id: 5,
    group: "Hoje",
    name: "Demi Wilkinson",
    subject: "Consulta sobre relatório de sustentabilidade",
    preview: "Olá equipe, estou procurando a divulgação ESG mais recente para nossa próxima reunião do conselho.",
    time: "10:42 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 5,
    contact: {
      name: "Demi Wilkinson",
      role: "Gerente de Sustentabilidade",
      company: "BrightFuture Co.",
      email: "demi.wilkinson@weblabs.studio",
      phone: "+1 (415) 555-0189",
      website: "brightfuture.co",
      location: "San Francisco, CA, EUA",
      timezone: "PDT (UTC-7)",
      status: "Qualificado",
      qualifiedAt: "22 de jan. de 2026",
      tags: ["Sustentabilidade", "Enterprise", "FinServ"],
    },
    messages: [
      {
        id: 501,
        align: "start",
        text: "Olá, estamos preparando materiais para o conselho e precisamos de sua divulgação ESG mais recente, especialmente a seção de pegada de carbono.",
        time: "10:42 AM",
      },
      {
        id: 502,
        align: "end",
        text: "Olá Demi. Posso compartilhar o relatório de 2025 e o apêndice de contabilidade de carbono. Você também precisa dos dados brutos de emissões?",
        time: "10:44 AM",
      },
      {
        id: 503,
        align: "start",
        text: "Sim, os dados brutos do Escopo 3 ajudariam. Nosso pacote para o conselho precisa dos números da cadeia de suprimentos, não apenas do resumo.",
        time: "10:47 AM",
      },
      {
        id: 504,
        align: "end",
        text: "Entendido. Enviarei o resumo executivo, o CSV do Escopo 3 e a nota metodológica em um único pacote.",
        time: "10:49 AM",
        reaction: "\u{1F44D}",
      },
      { id: 505, align: "start", text: "Perfeito. Isso deve cobrir tudo para quinta-feira.", time: "10:50 AM" },
    ],
  },
  {
    id: 6,
    group: "Hoje",
    name: "Candice Wu",
    subject: "Exportação em lote continua expirando",
    preview: "Tentei três vezes esta manhã. Chega a cerca de 60% e então lança erro de gateway.",
    time: "10:15 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Candice Wu",
      role: "Engenheira de Dados",
      company: "Harbor Ops",
      email: "candice.wu@sandbox.dev",
      phone: "+1 (206) 555-0172",
      website: "harborops.com",
      location: "Seattle, WA, EUA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      qualifiedAt: "10 de mai. de 2026",
      tags: ["Dados", "Desempenho"],
    },
    messages: [
      {
        id: 601,
        align: "start",
        text: "A exportação em lote continua expirando. Ela chega a cerca de 60 por cento e então lança erro de gateway.",
        time: "10:15 AM",
      },
      {
        id: 602,
        align: "end",
        text: "Obrigado, Candice. Isso é para a exportação completa do histórico de envios ou um intervalo de datas filtrado?",
        time: "10:12 AM",
      },
      {
        id: 603,
        align: "start",
        text: "Histórico completo. Precisamos disso para uma migração de armazenamento, então o arquivo é bem grande.",
        time: "10:09 AM",
      },
      {
        id: 604,
        align: "end",
        text: "Vou enfileirar como exportação assíncrona e enviar o link de download por e-mail quando terminar. Isso evita o timeout do gateway.",
        time: "10:06 AM",
        reaction: "\u2705",
      },
    ],
  },
  {
    id: 7,
    group: "Hoje",
    name: "Natali Craig",
    subject: "Fatura INV-4821 ainda marcada como não paga",
    preview: "Nosso pagamento foi compensado na sexta-feira — print da confirmação anexado aqui.",
    time: "9:58 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 1,
    contact: {
      name: "Natali Craig",
      role: "Gerente Financeira",
      company: "Lumen Studio",
      email: "natali.craig@weblabs.studio",
      phone: "+39 02 5555 0184",
      website: "lumenstudio.co",
      location: "Milão, Itália",
      timezone: "CEST (UTC+2)",
      status: "Cliente",
      qualifiedAt: "14 de out. de 2025",
      tags: ["Cobrança", "SMB"],
    },
    messages: [
      {
        id: 701,
        align: "start",
        text: "A fatura INV-4821 ainda aparece como não paga, mesmo que nossa transferência bancária tenha sido compensada na última sexta-feira.",
        time: "9:58 AM",
      },
      {
        id: 702,
        align: "end",
        text: "Obrigado, Natali. Você pode enviar a referência da transferência para que eu possa comparar com os registros do nosso processador de pagamento?",
        time: "9:54 AM",
      },
      {
        id: 703,
        align: "start",
        text: "Acabei de anexar o print da confirmação. A referência termina em 9147.",
        time: "9:50 AM",
      },
      {
        id: 704,
        align: "end",
        text: "Encontrei. O pagamento foi recebido mas não conciliado à fatura. Marquei a INV-4821 como paga.",
        time: "9:46 AM",
        reaction: "\u{1F64F}",
      },
    ],
  },
  {
    id: 8,
    group: "Hoje",
    name: "Drew Cano",
    subject: "Documentos de integração para novo funcionário — por onde começar?",
    preview: "Temos um novo desenvolvedor backend começando na segunda. Preciso da lista de verificação padrão e etapas de acesso ao repositório.",
    time: "9:32 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Drew Cano",
      role: "Gerente de Engenharia",
      company: "AtlasWorks",
      email: "drew.cano@internal.tools",
      phone: "+1 (512) 555-0166",
      website: "atlasworks.co",
      location: "Austin, TX, EUA",
      timezone: "CDT (UTC-5)",
      status: "Cliente",
      qualifiedAt: "3 de ago. de 2025",
      tags: ["Integração", "Plataforma", "Promotor NPS"],
    },
    messages: [
      {
        id: 801,
        align: "start",
        text: "Temos um desenvolvedor backend começando na segunda. Qual é o melhor caminho de integração para acesso ao repositório e configuração do ambiente?",
        time: "9:32 AM",
      },
      {
        id: 802,
        align: "end",
        text: "Olá Drew. Enviarei a lista de verificação padrão de engenharia e o link de convite para o workspace do desenvolvedor.",
        time: "9:28 AM",
      },
      {
        id: 803,
        align: "start",
        text: "Ótimo. Por favor, inclua as credenciais do staging e quaisquer regras de nomenclatura de branches, se estiverem documentadas.",
        time: "9:24 AM",
      },
      {
        id: 804,
        align: "end",
        text: "Vou fazer. Adicionarei a solicitação de acesso ao staging e nossas convenções de repositório na mesma thread.",
        time: "9:20 AM",
        reaction: "\u{1F44D}",
      },
    ],
  },
  {
    id: 9,
    group: "Hoje",
    name: "Orlando Diggs",
    subject: "Downgrade do plano Enterprise para Pro",
    preview: "Estamos encerrando o projeto no final do trimestre. Há uma taxa de cancelamento antecipado?",
    time: "9:12 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Orlando Diggs",
      role: "CTO",
      company: "Northstar Workspace",
      email: "orlando.diggs@acme.inc",
      phone: "+1 (720) 555-0195",
      website: "northstarworkspace.com",
      location: "Denver, CO, EUA",
      timezone: "MDT (UTC-6)",
      status: "Em Risco",
      qualifiedAt: "1 de dez. de 2025",
      tags: ["Risco de Evasão", "Enterprise", "Downgrade"],
    },
    messages: [
      {
        id: 901,
        align: "start",
        text: "Estamos encerrando o projeto atual e precisamos fazer downgrade do plano Enterprise para Pro no final do trimestre.",
        time: "9:12 AM",
      },
      {
        id: 902,
        align: "end",
        text: "Entendido, Orlando. Posso explicar o caminho do downgrade e confirmar se alguma condição contratual se aplica.",
        time: "9:08 AM",
      },
      {
        id: 903,
        align: "start",
        text: "A principal questão é se há uma taxa de cancelamento antecipado ou se podemos mudar na renovação.",
        time: "9:04 AM",
      },
      {
        id: 904,
        align: "end",
        text: "Seu acordo permite downgrade na renovação com 30 dias de antecedência. Enviarei a data e o resumo do impacto nas funcionalidades.",
        time: "9:00 AM",
      },
    ],
  },
  {
    id: 10,
    group: "Hoje",
    name: "Andi Lane",
    subject: "Limite de taxa da API atingindo forte durante o pico",
    preview: "Nossos jobs em lote estão recebendo erros 429 a cada 15 minutos entre 9 e 11h. Precisamos de um aumento.",
    time: "8:47 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 3,
    contact: {
      name: "Andi Lane",
      role: "Líder de Backend",
      company: "LedgerLoop",
      email: "andi.lane@weblabs.studio",
      phone: "+353 1 555 0189",
      website: "ledgerloop.io",
      location: "Dublin, Irlanda",
      timezone: "IST (UTC+1)",
      status: "Lead",
      qualifiedAt: "19 de abr. de 2026",
      tags: ["API", "Escalabilidade", "Enterprise"],
    },
    messages: [
      {
        id: 1001,
        align: "start",
        text: "Nossos jobs em lote estão recebendo erros 429 a cada poucos minutos durante o horário de pico. Precisamos de um aumento temporário no limite de taxa.",
        time: "8:47 AM",
      },
      {
        id: 1002,
        align: "end",
        text: "Obrigado, Andi. Quais chaves de API estão afetadas e qual janela de pico você está vendo?",
        time: "8:43 AM",
      },
      {
        id: 1003,
        align: "start",
        text: "Principalmente invoice-sync e customer-import, entre 9 e 11h horário de Dublin.",
        time: "8:39 AM",
      },
      {
        id: 1004,
        align: "end",
        text: "Posso aumentar o limite para essas chaves por sete dias enquanto revisamos sua cota de longo prazo.",
        time: "8:35 AM",
      },
    ],
  },
  {
    id: 11,
    group: "Hoje",
    name: "Kate Morrison",
    subject: "Certificado SSL do domínio personalizado expirou durante a noite",
    preview: "Usuários estão vendo avisos de certificado ao acessar nossa página de loja. Isso é urgente.",
    time: "8:05 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 6,
    contact: {
      name: "Kate Morrison",
      role: "Gerente de Produto",
      company: "Storefront Labs",
      email: "kate.morrison@weblabs.studio",
      phone: "+1 (213) 555-0192",
      website: "storefrontlabs.com",
      location: "Los Angeles, CA, EUA",
      timezone: "PDT (UTC-7)",
      status: "Cliente",
      qualifiedAt: "2 de jun. de 2026",
      tags: ["Urgente", "SMB", "SSL"],
    },
    messages: [
      {
        id: 1101,
        align: "start",
        text: "Nosso domínio personalizado começou a mostrar avisos de certificado durante a noite. Os usuários não conseguem finalizar a compra.",
        time: "8:05 AM",
      },
      {
        id: 1102,
        align: "end",
        text: "Obrigado, Kate. Estou verificando a tarefa de renovação do certificado e a validação de DNS agora.",
        time: "8:01 AM",
      },
      {
        id: 1103,
        align: "start",
        text: "O DNS não mudou do nosso lado. O aviso diz que o certificado expirou à meia-noite.",
        time: "7:57 AM",
      },
      {
        id: 1104,
        align: "end",
        text: "A tarefa de renovação falhou na validação CAA. Emiti o certificado manualmente e ele está se propagando.",
        time: "7:53 AM",
        reaction: "\u26A1",
      },
    ],
  },
  {
    id: 12,
    group: "Hoje",
    name: "Alec Whitten",
    subject: "Atualização para cobrança anual — há desconto?",
    preview: "Estamos prontos para nos comprometer com o ano. Você pode enviar a tabela de preços anual?",
    time: "7:38 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Alec Whitten",
      role: "Diretor de TI",
      company: "Crescent Media Group",
      email: "alec.whitten@internal.tools",
      phone: "+974 4455 1234",
      website: "crescentmedia.qa",
      location: "Doha, Catar",
      timezone: "AST (UTC+3)",
      status: "Qualificado",
      qualifiedAt: "28 de mai. de 2026",
      tags: ["Atualização", "Enterprise", "Mídia"],
    },
    messages: [
      {
        id: 1201,
        align: "start",
        text: "Estamos prontos para mudar para cobrança anual. Há desconto se nos comprometermos com o ano inteiro?",
        time: "7:38 AM",
      },
      {
        id: 1202,
        align: "end",
        text: "Olá Alec. Sim, a cobrança anual inclui desconto. Posso enviar uma cotação com os termos anuais hoje.",
        time: "7:34 AM",
      },
      {
        id: 1203,
        align: "start",
        text: "Por favor, inclua as licenças da equipe de mídia e o complemento de analytics na cotação.",
        time: "7:30 AM",
      },
      {
        id: 1204,
        align: "end",
        text: "Feito. Incluirei ambos e marcarei a cotação como pré-pagamento anual para que o procurement possa revisar rapidamente.",
        time: "7:26 AM",
        reaction: "\u2705",
      },
    ],
  },
  {
    id: 13,
    group: "Hoje",
    name: "Ariana Decker",
    subject: "Bug: seletor de data defasado em um dia nos relatórios",
    preview: "Selecionar 5 de junho produz 4 de junho na exportação CSV. Print de tela anexado como referência.",
    time: "6:52 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Ariana Decker",
      role: "Analista de QA",
      company: "Northstar Health",
      email: "ariana.decker@weblabs.studio",
      phone: "+1 (617) 555-0188",
      website: "northstarhealth.com",
      location: "Boston, MA, EUA",
      timezone: "EDT (UTC-4)",
      status: "Cliente",
      qualifiedAt: "14 de mar. de 2026",
      tags: ["Bug", "Relatórios"],
    },
    messages: [
      {
        id: 1301,
        align: "start",
        text: "O seletor de data do relatório está defasado em um dia. Selecionar 5 de junho exporta 4 de junho no CSV.",
        time: "6:52 AM",
      },
      {
        id: 1302,
        align: "end",
        text: "Obrigado, Ariana. A interface mostra a data correta antes da exportação, ou também está errada lá?",
        time: "6:48 AM",
      },
      {
        id: 1303,
        align: "start",
        text: "A interface parece correta. Apenas a saída CSV está deslocada.",
        time: "6:44 AM",
      },
      {
        id: 1304,
        align: "end",
        text: "Isso aponta para conversão de fuso horário na tarefa de exportação. Vou anexar seu print ao chamado do bug.",
        time: "6:40 AM",
      },
    ],
  },
  {
    id: 14,
    group: "Hoje",
    name: "Steven Tey",
    subject: "Falhas na entrega de webhooks para integração Zapier",
    preview: "Recebendo erros 500 intermitentes no endpoint de webhook desde aproximadamente 2h UTC. Logs vinculados.",
    time: "6:10 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Steven Tey",
      role: "Arquiteto de Soluções",
      company: "BridgeWork Inc.",
      email: "steven.tey@sandbox.dev",
      phone: "+1 (404) 555-0141",
      website: "bridgework.io",
      location: "Atlanta, GA, EUA",
      timezone: "EDT (UTC-4)",
      status: "Lead",
      qualifiedAt: "8 de abr. de 2026",
      tags: ["Integrações", "Plataforma", "Zapier"],
    },
    messages: [
      {
        id: 1401,
        align: "start",
        text: "A entrega do webhook do Zapier está falhando intermitentemente com erros 500. Começou por volta das 2h UTC.",
        time: "6:10 AM",
      },
      {
        id: 1402,
        align: "end",
        text: "Obrigado, Steven. Você pode compartilhar um ID de entrega falha e o caminho do endpoint?",
        time: "6:06 AM",
      },
      {
        id: 1403,
        align: "start",
        text: "ID de entrega wh_72a9. Endpoint é /hooks/zapier/customer-created.",
        time: "6:02 AM",
      },
      {
        id: 1404,
        align: "end",
        text: "Encontrei tentativas de retry acumuladas nesse endpoint. Estamos aumentando a capacidade dos workers e reproduzindo as entregas falhas.",
        time: "5:58 AM",
      },
    ],
  },
  {
    id: 15,
    group: "Hoje",
    name: "Lori Bryson",
    subject: "Solicitação: RBAC granular para líderes de equipe",
    preview: "Nossos líderes de engenharia precisam de acesso somente leitura em produção, mas acesso total de escrita no staging.",
    time: "5:44 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Lori Bryson",
      role: "Arquiteta de Plataforma",
      company: "KumoWorks K.K.",
      email: "lori.bryson@acme.inc",
      phone: "+81 3 5555 0173",
      website: "kumoworks.jp",
      location: "Tóquio, Japão",
      timezone: "JST (UTC+9)",
      status: "Qualificado",
      qualifiedAt: "9 de fev. de 2026",
      tags: ["RBAC", "Enterprise", "Solicitação de Recurso"],
    },
    messages: [
      {
        id: 1501,
        align: "start",
        text: "Nossos líderes de equipe precisam de acesso somente leitura em produção, mas permissões de escrita totais no staging. O RBAC suporta essa divisão?",
        time: "5:44 AM",
      },
      {
        id: 1502,
        align: "end",
        text: "Sim, Lori. Você pode separar o escopo do ambiente do nível de permissão. Enviarei o exemplo de política.",
        time: "5:40 AM",
      },
      {
        id: 1503,
        align: "start",
        text: "Ótimo. Também precisamos de logs de auditoria para mostrar quem alterou as configurações do staging.",
        time: "5:36 AM",
      },
      {
        id: 1504,
        align: "end",
        text: "Isso está incluído. Adicionarei os filtros de log de auditoria ao exemplo para que seus líderes possam testar.",
        time: "5:32 AM",
      },
    ],
  },
  {
    id: 16,
    group: "Hoje",
    name: "Koray Okumus",
    subject: "Aplicativo mobile trava no Android 14 após atualização",
    preview: "Três usuários relataram o mesmo travamento na inicialização. Rastreamento de pilha do Firebase anexado.",
    time: "5:18 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 3,
    contact: {
      name: "Koray Okumus",
      role: "Líder Mobile",
      company: "MobiSolar Ltd.",
      email: "koray.okumus@weblabs.studio",
      phone: "+254 711 555 0182",
      website: "mobisolar.co.ke",
      location: "Nairóbi, Quênia",
      timezone: "EAT (UTC+3)",
      status: "Cliente",
      qualifiedAt: "5 de jan. de 2026",
      tags: ["Mobile", "Android", "Bug"],
    },
    messages: [
      {
        id: 1601,
        align: "start",
        text: "Nossos usuários Android na versão 14 estão vendo travamentos logo após a tela de apresentação. O Firebase mostra três dispositivos afetados até agora.",
        time: "5:18 AM",
      },
      {
        id: 1602,
        align: "end",
        text: "Obrigado por reportar isso, Koray. Você pode compartilhar o link do crashlytics do Firebase? Vou acionar a equipe mobile.",
        time: "5:05 AM",
      },
      {
        id: 1603,
        align: "start",
        text: "Claro, vinculei o rastreamento de pilha no chamado. Parece ser um ponteiro nulo na inicialização do módulo de pagamento.",
        time: "4:52 AM",
      },
      {
        id: 1604,
        align: "end",
        text: "Encontrei — há um caso extremo quando o Google Play Services não está atualizado. Estamos enviando uma correção agora.",
        time: "4:40 AM",
      },
    ],
  },
  // Ontem
  {
    id: 17,
    group: "Ontem",
    name: "Josh Miller",
    subject: "Proposta de parceria para o mercado latino-americano",
    preview: "Estamos expandindo para México e Brasil no próximo trimestre. Adoraríamos explorar um acordo de revendedor.",
    time: "Ontem",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Josh Miller",
      role: "CEO",
      company: "Nexo Digital MX",
      email: "josh.miller@internal.tools",
      phone: "+52 55 5555 0165",
      website: "nexodigital.mx",
      location: "Cidade do México, México",
      timezone: "CST (UTC-6)",
      status: "Lead",
      qualifiedAt: "15 de mai. de 2026",
      tags: ["Parceria", "LATAM", "Revendedor"],
    },
    messages: [
      {
        id: 1701,
        align: "start",
        text: "Estamos expandindo para México e Brasil no próximo trimestre e queremos explorar uma parceria de revendedor.",
        time: "Ontem",
      },
      {
        id: 1702,
        align: "end",
        text: "Obrigado, Josh. Isso parece alinhado com nossos planos para a LATAM. Você já tem segmentos de clientes-alvo em mente?",
        time: "Ontem",
      },
      {
        id: 1703,
        align: "start",
        text: "Principalmente equipes de logística e varejo do mercado intermediário. Podemos trazer pipeline inicial se os termos de revendedor funcionarem.",
        time: "Ontem",
      },
      {
        id: 1704,
        align: "end",
        text: "Vou apresentá-lo ao nosso líder de parcerias e compartilhar o panorama dos níveis de revendedor antes de sexta-feira.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 18,
    group: "Ontem",
    name: "Mollie Hall",
    subject: "Exportação de dados — preciso de todos os logs de maio",
    preview: "Nossa auditoria de conformidade começa na próxima semana. Preciso de um dump completo de log de atividade para os auditores.",
    time: "Ontem",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Mollie Hall",
      role: "Oficial de Conformidade",
      company: "NovaPay Ltd.",
      email: "mollie.hall@weblabs.studio",
      phone: "+44 20 5555 0178",
      website: "novapay.co.uk",
      location: "Londres, Reino Unido",
      timezone: "BST (UTC+1)",
      status: "Cliente",
      qualifiedAt: "8 de nov. de 2025",
      tags: ["Conformidade", "FinServ", "Auditoria"],
    },
    messages: [
      {
        id: 1801,
        align: "start",
        text: "Nossa auditoria de conformidade começa na próxima semana. Precisamos dos logs de atividade para todos os eventos do workspace de maio.",
        time: "Ontem",
      },
      {
        id: 1802,
        align: "end",
        text: "Olá Mollie. Podemos exportar atividade de administrador, eventos de login e logs de acesso a arquivos. Os auditores precisam em CSV ou JSON?",
        time: "Ontem",
      },
      {
        id: 1803,
        align: "start",
        text: "CSV está bom, mas precisa de IDs de usuário e carimbos de data/hora em UTC.",
        time: "Ontem",
      },
      {
        id: 1804,
        align: "end",
        text: "Entendido. Prepararei a exportação de maio com carimbos de data/hora em UTC e enviarei pelo link seguro de arquivo.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 19,
    group: "Ontem",
    name: "Rene Wells",
    subject: "Opções de white-label para nosso programa de revendedores",
    preview: "Temos cinco parceiros perguntando sobre dashboards com marca. Vocês oferecem níveis de white-label?",
    time: "Ontem",
    isUnread: true,
    isOnline: true,
    unreadCount: 1,
    contact: {
      name: "Rene Wells",
      role: "Diretor de Produto",
      company: "Jambo Digital KE",
      email: "rene.wells@acme.inc",
      phone: "+254 722 555 0194",
      website: "jambodigital.ke",
      location: "Nairóbi, Quênia",
      timezone: "EAT (UTC+3)",
      status: "Qualificado",
      qualifiedAt: "25 de abr. de 2026",
      tags: ["White-Label", "Revendedor", "Plataforma"],
    },
    messages: [
      {
        id: 1901,
        align: "start",
        text: "Temos cinco parceiros revendedores perguntando se o dashboard pode ser white-label.",
        time: "Ontem",
      },
      {
        id: 1902,
        align: "end",
        text: "Olá Rene. O white-labeling está disponível no nível de parceiro. Eles estão perguntando sobre domínio personalizado, logo ou controle total do tema?",
        time: "Ontem",
      },
      {
        id: 1903,
        align: "start",
        text: "Idealmente, todos os três. Eles querem seu próprio domínio e relatórios com marca para clientes.",
        time: "Ontem",
      },
      {
        id: 1904,
        align: "end",
        text: "Isso é suportado. Enviarei o documento do nível de parceiro e um modelo de relatório com marca de exemplo.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 20,
    group: "Ontem",
    name: "Rylee Howard",
    subject: "Implantação de obrigatoriedade de MFA — dúvidas",
    preview: "Nossa equipe de segurança quer saber se o fallback por SMS ainda é suportado após a data de obrigatoriedade.",
    time: "Ontem",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Rylee Howard",
      role: "Arquiteta de Segurança",
      company: "Grupo Financiero Sur",
      email: "rylee.howard@sandbox.dev",
      phone: "+57 601 555 0180",
      website: "gfsur.com.co",
      location: "Bogotá, Colômbia",
      timezone: "COT (UTC-5)",
      status: "Qualificado",
      qualifiedAt: "30 de mar. de 2026",
      tags: ["Segurança", "Enterprise", "MFA"],
    },
    messages: [
      {
        id: 2001,
        align: "start",
        text: "Nossa equipe de segurança tem dúvidas sobre a implantação da obrigatoriedade de MFA. O fallback por SMS ainda é suportado?",
        time: "Ontem",
      },
      {
        id: 2002,
        align: "end",
        text: "Olá Rylee. O fallback por SMS continua disponível, mas recomendamos aplicativos autenticadores ou chaves de segurança para administradores.",
        time: "Ontem",
      },
      {
        id: 2003,
        align: "start",
        text: "Podemos obrigar chaves de segurança para administradores e permitir SMS apenas para contratados?",
        time: "Ontem",
      },
      {
        id: 2004,
        align: "end",
        text: "Sim. Você pode configurar isso por grupo de usuários. Enviarei os passos de configuração da política.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 21,
    group: "Ontem",
    name: "Sienna Hewitt",
    subject: "Itens de linha faltando na exportação CSV",
    preview: "A exportação da fatura de janeiro está com três itens de linha a menos. A versão PDF está correta, porém.",
    time: "Ontem",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Sienna Hewitt",
      role: "Diretora Financeira",
      company: "Volta Energy AB",
      email: "sienna.hewitt@weblabs.studio",
      phone: "+46 73 555 0168",
      website: "voltaenergy.se",
      location: "Malmö, Suécia",
      timezone: "CEST (UTC+2)",
      status: "Cliente",
      qualifiedAt: "12 de set. de 2025",
      tags: ["Cobrança", "Exportação", "Bug"],
    },
    messages: [
      {
        id: 2101,
        align: "start",
        text: "O CSV da fatura de janeio está com três itens de linha faltando. A fatura em PDF parece correta.",
        time: "Ontem",
      },
      {
        id: 2102,
        align: "end",
        text: "Obrigado, Sienna. Os itens de linha faltando são descontos, cobranças de uso ou impostos?",
        time: "Ontem",
      },
      {
        id: 2103,
        align: "start",
        text: "Dois são cobranças de uso e um é um ajuste de imposto. Todos aparecem no PDF.",
        time: "Ontem",
      },
      {
        id: 2104,
        align: "end",
        text: "Encontrei um filtro de exportação excluindo linhas de uso ajustadas. Vamos corrigir e regenerar o CSV de janeio para você.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 22,
    group: "Ontem",
    name: "Noah Pierre",
    subject: "Solicitação de demonstração para equipe de procurement — sexta-feira",
    preview: "Preciso de uma visita de 30 minutos ao portal de fornecedores para nossos líderes financeiros nesta sexta-feira.",
    time: "Ontem",
    isUnread: true,
    isOnline: false,
    unreadCount: 5,
    contact: {
      name: "Noah Pierre",
      role: "Gerente de Procurement",
      company: "First Atlantic Bank NG",
      email: "noah.pierre@weblabs.studio",
      phone: "+234 805 555 0125",
      website: "firstatlanticbank.ng",
      location: "Abuja, Nigéria",
      timezone: "WAT (UTC+1)",
      status: "Lead",
      qualifiedAt: "20 de mai. de 2026",
      tags: ["Demonstração", "FinServ", "Enterprise"],
    },
    messages: [
      {
        id: 2201,
        align: "start",
        text: "Poderíamos agendar uma demonstração de 30 minutos para nossos líderes de procurement e finanças nesta sexta-feira?",
        time: "Ontem",
      },
      {
        id: 2202,
        align: "end",
        text: "Com certeza, Noah. A visita deve focar no onboarding de fornecedores, aprovações ou relatórios?",
        time: "Ontem",
      },
      {
        id: 2203,
        align: "start",
        text: "O onboarding de fornecedores e o roteamento de aprovações são a prioridade. Relatórios podem ser uma visão geral rápida.",
        time: "Ontem",
      },
      {
        id: 2204,
        align: "end",
        text: "Ótimo. Enviarei um horário de sexta com uma pauta personalizada para esses dois fluxos de trabalho.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 23,
    group: "Ontem",
    name: "Eve Lechner",
    subject: "Integração SSO com Azure AD",
    preview: "Estamos migrando do Okta para o Azure AD. Qual é o cronograma típico de configuração do SSO?",
    time: "Ontem",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Eve Lechner",
      role: "Diretora de TI",
      company: "Northlane IT",
      email: "eve.lechner@acme.inc",
      phone: "+420 222 555 013",
      website: "northlaneit.com",
      location: "Praga, Tchéquia",
      timezone: "CEST (UTC+2)",
      status: "Qualificado",
      qualifiedAt: "14 de fev. de 2026",
      tags: ["SSO", "Azure", "Enterprise"],
    },
    messages: [
      {
        id: 2301,
        align: "start",
        text: "Estamos migrando do Okta para o Azure AD e precisamos entender o cronograma de configuração do SSO.",
        time: "Ontem",
      },
      {
        id: 2302,
        align: "end",
        text: "Olá Eve. A configuração típica do SSO com Azure AD leva de um a dois dias úteis após a troca de metadados.",
        time: "Ontem",
      },
      {
        id: 2303,
        align: "start",
        text: "Podemos compartilhar os metadados hoje. Haverá tempo de inatividade durante a troca?",
        time: "Ontem",
      },
      {
        id: 2304,
        align: "end",
        text: "Sem tempo de inatividade se testarmos com um grupo piloto primeiro. Enviarei a lista de verificação do Azure AD e o plano de implantação.",
        time: "Ontem",
      },
    ],
  },
  {
    id: 24,
    group: "Ontem",
    name: "Zahir McClure",
    subject: "Solicitação de cancelamento — proprietário da conta saiu",
    preview: "Nosso líder de operações renunciou na semana passada. Preciso transferir a propriedade para mim antes de podermos cancelar.",
    time: "Ontem",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Zahir McClure",
      role: "Diretor de Operações",
      company: "Cedar Grove Ventures",
      email: "zahir.mcclure@internal.tools",
      phone: "+1 (615) 555-0175",
      website: "cedargrove.vc",
      location: "Nashville, TN, EUA",
      timezone: "CDT (UTC-5)",
      status: "Em Risco",
      qualifiedAt: "15 de jun. de 2025",
      tags: ["Risco de Evasão", "Conta", "SMB"],
    },
    messages: [
      {
        id: 2401,
        align: "start",
        text: "Nosso líder de operações Jamal renunciou na semana passada e ele era o único proprietário da conta. Preciso que a propriedade seja transferida para mim antes de podermos prosseguir com qualquer coisa.",
        time: "Ontem",
      },
      {
        id: 2402,
        align: "end",
        text: "Olá Zahir, posso ajudar com isso. Precisaremos de verificação — você pode confirmar seu cargo e fornecer uma cópia do aviso de renúncia do Jamal?",
        time: "Ontem",
      },
      {
        id: 2403,
        align: "start",
        text: "Com certeza. Sou o Diretor de Operações. Anexei o aviso assinado dele e a confirmação do RH.",
        time: "Ontem",
      },
      {
        id: 2404,
        align: "end",
        text: "Verificado. Iniciei a transferência de propriedade. Leva cerca de 2 horas para se propagar. Você receberá um e-mail de confirmação quando terminar.",
        time: "Ontem",
      },
    ],
  },
];

export const currentUser = {
  name: "Arham Khan",
  email: "arham.khan@weblabs.studio",
};
