export type Role = {
  role: string;
  group: string;
  accessLevel: string;
  users: number;
  permissionSets: string[];
  lastReview: string;
  owner: string;
  status: "Ativo" | "Precisa de revisão";
};

export const roles: Role[] = [
  {
    role: "Owner",
    group: "Precisa de revisão",
    accessLevel: "Total",
    users: 2,
    permissionSets: ["Users", "Settings", "Billing", "Reports", "Integrations", "Audit Logs"],
    lastReview: "12 de abr. de 2025",
    owner: "System",
    status: "Precisa de revisão",
  },
  {
    role: "Admin",
    group: "Precisa de revisão",
    accessLevel: "Total",
    users: 5,
    permissionSets: ["Users", "Settings", "Reports", "Billing", "Integrations"],
    lastReview: "15 de abr. de 2025",
    owner: "Jane Doe",
    status: "Precisa de revisão",
  },
  {
    role: "Manager",
    group: "Precisa de revisão",
    accessLevel: "Delimitado",
    users: 12,
    permissionSets: ["Users", "Reports", "Projects", "Tasks"],
    lastReview: "18 de abr. de 2025",
    owner: "Jane Doe",
    status: "Precisa de revisão",
  },
  {
    role: "Support",
    group: "Funções do sistema",
    accessLevel: "Delimitado",
    users: 8,
    permissionSets: ["Users", "Tickets", "Reports", "Knowledge Base"],
    lastReview: "1 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Analyst",
    group: "Funções do sistema",
    accessLevel: "Delimitado",
    users: 6,
    permissionSets: ["Reports", "Analytics", "Dashboards", "Exports"],
    lastReview: "5 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Guest",
    group: "Funções do sistema",
    accessLevel: "Somente leitura",
    users: 14,
    permissionSets: ["Reports", "Dashboards"],
    lastReview: "6 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Service",
    group: "Funções do sistema",
    accessLevel: "Acesso API",
    users: 3,
    permissionSets: ["Integrations", "API Keys", "Webhooks", "Logs"],
    lastReview: "22 de abr. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Billing",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 3,
    permissionSets: ["Billing", "Invoices", "Payments", "Reports"],
    lastReview: "28 de abr. de 2025",
    owner: "Alex Kim",
    status: "Ativo",
  },
  {
    role: "Marketing",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 9,
    permissionSets: ["Users", "Reports", "Campaigns", "Analytics", "Exports"],
    lastReview: "2 de mai. de 2025",
    owner: "Alex Kim",
    status: "Ativo",
  },
  {
    role: "Developer",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 10,
    permissionSets: ["Repos", "Deployments", "Settings", "API Keys", "Logs"],
    lastReview: "3 de mai. de 2025",
    owner: "Chris Lee",
    status: "Ativo",
  },
  {
    role: "Project Lead",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 7,
    permissionSets: ["Projects", "Tasks", "Reports", "Users", "Settings"],
    lastReview: "30 de abr. de 2025",
    owner: "Chris Lee",
    status: "Ativo",
  },
  {
    role: "Finance Viewer",
    group: "Funções personalizadas",
    accessLevel: "Somente leitura",
    users: 4,
    permissionSets: ["Billing", "Reports", "Invoices", "Dashboards"],
    lastReview: "7 de mai. de 2025",
    owner: "Jane Doe",
    status: "Ativo",
  },
];
