export type Role = {
  role: string;
  group: string;
  accessLevel: string;
  users: number;
  permissionSets: string[];
  lastReview: string;
  owner: string;
  status: "Ativo" | "Precisa de revisão";
};

export const roles: Role[] = [
  {
    role: "Proprietário",
    group: "Precisa de revisão",
    accessLevel: "Total",
    users: 2,
    permissionSets: ["Usuários", "Configurações", "Faturamento", "Relatórios", "Integrações", "Registros de Auditoria"],
    lastReview: "12 de abr. de 2025",
    owner: "Sistema",
    status: "Precisa de revisão",
  },
  {
    role: "Administrador",
    group: "Precisa de revisão",
    accessLevel: "Total",
    users: 5,
    permissionSets: ["Usuários", "Configurações", "Relatórios", "Faturamento", "Integrações"],
    lastReview: "15 de abr. de 2025",
    owner: "Jane Doe",
    status: "Precisa de revisão",
  },
  {
    role: "Gerente",
    group: "Precisa de revisão",
    accessLevel: "Delimitado",
    users: 12,
    permissionSets: ["Usuários", "Relatórios", "Projetos", "Tarefas"],
    lastReview: "18 de abr. de 2025",
    owner: "Jane Doe",
    status: "Precisa de revisão",
  },
  {
    role: "Suporte",
    group: "Funções do sistema",
    accessLevel: "Delimitado",
    users: 8,
    permissionSets: ["Usuários", "Chamados", "Relatórios", "Base de Conhecimento"],
    lastReview: "1 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Analista",
    group: "Funções do sistema",
    accessLevel: "Delimitado",
    users: 6,
    permissionSets: ["Relatórios", "Análises", "Painéis", "Exportações"],
    lastReview: "5 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Convidado",
    group: "Funções do sistema",
    accessLevel: "Somente leitura",
    users: 14,
    permissionSets: ["Relatórios", "Painéis"],
    lastReview: "6 de mai. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Serviço",
    group: "Funções do sistema",
    accessLevel: "Acesso API",
    users: 3,
    permissionSets: ["Integrações", "Chaves de API", "Webhooks", "Registros"],
    lastReview: "22 de abr. de 2025",
    owner: "System",
    status: "Ativo",
  },
  {
    role: "Faturamento",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 3,
    permissionSets: ["Faturamento", "Faturas", "Pagamentos", "Relatórios"],
    lastReview: "28 de abr. de 2025",
    owner: "Alex Kim",
    status: "Ativo",
  },
  {
    role: "Marketing",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 9,
    permissionSets: ["Usuários", "Relatórios", "Campanhas", "Análises", "Exportações"],
    lastReview: "2 de mai. de 2025",
    owner: "Alex Kim",
    status: "Ativo",
  },
  {
    role: "Desenvolvedor",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 10,
    permissionSets: ["Repositórios", "Implantações", "Configurações", "Chaves de API", "Registros"],
    lastReview: "3 de mai. de 2025",
    owner: "Chris Lee",
    status: "Ativo",
  },
  {
    role: "Líder de Projeto",
    group: "Funções personalizadas",
    accessLevel: "Delimitado",
    users: 7,
    permissionSets: ["Projetos", "Tarefas", "Relatórios", "Usuários", "Configurações"],
    lastReview: "30 de abr. de 2025",
    owner: "Chris Lee",
    status: "Ativo",
  },
  {
    role: "Visualizador Financeiro",
    group: "Funções personalizadas",
    accessLevel: "Somente leitura",
    users: 4,
    permissionSets: ["Faturamento", "Relatórios", "Faturas", "Painéis"],
    lastReview: "7 de mai. de 2025",
    owner: "Jane Doe",
    status: "Ativo",
  },
];
