export type UserStatus = "Ativo" | "Convite pendente" | "Desativado" | "Bloqueado" | "Suspenso";

const teamValues = [
  "Plataforma",
  "Crescimento",
  "Receita",
  "Operações de Cliente",
  "Ferramentas Internas",
  "Conformidade",
  "Operações de Pessoal",
  "Financeiro",
] as const;

export type UserTeam = (typeof teamValues)[number];

export type UserRow = {
  email: string;
  joinedDate: string;
  lastActive: number;
  name: string;
  role: string;
  status: UserStatus;
  team: UserTeam;
  workspace: string[];
};

export const users: UserRow[] = [
  {
    name: "Olivia Rhye",
    email: "olivia.rhye@weblabs.studio",
    role: "Proprietário do Espaço de Trabalho",
    status: "Ativo",
    team: "Plataforma",
    workspace: ["Weblabs Studio", "Ferramentas Internas"],
    joinedDate: "24 de jun. de 2024, 9:23",
    lastActive: 0,
  },
  {
    name: "Phoenix Baker",
    email: "phoenix.baker@weblabs.studio",
    role: "Administrador",
    status: "Ativo",
    team: "Crescimento",
    workspace: ["Weblabs Studio"],
    joinedDate: "15 de mar. de 2023, 14:45",
    lastActive: 5,
  },
  {
    name: "Lana Steiner",
    email: "lana.steiner@acme.inc",
    role: "Administrador de Cobrança",
    status: "Ativo",
    team: "Receita",
    workspace: ["Acme Inc."],
    joinedDate: "10 de abr. de 2022, 11:30",
    lastActive: 14 * 24 * 60,
  },
  {
    name: "Demi Wilkinson",
    email: "demi.wilkinson@weblabs.studio",
    role: "Administrador de Segurança",
    status: "Bloqueado",
    team: "Ferramentas Internas",
    workspace: ["Weblabs Studio", "Ferramentas Internas"],
    joinedDate: "28 de fev. de 2023, 18:15",
    lastActive: 60,
  },
  {
    name: "Candice Wu",
    email: "candice.wu@sandbox.dev",
    role: "Líder de Equipe",
    status: "Ativo",
    team: "Operações de Cliente",
    workspace: ["Sandbox"],
    joinedDate: "19 de mai. de 2024, 7:55",
    lastActive: 2 * 60,
  },
  {
    name: "Natali Craig",
    email: "natali.craig@weblabs.studio",
    role: "Colaborador",
    status: "Convite pendente",
    team: "Conformidade",
    workspace: ["Weblabs Studio"],
    joinedDate: "03 de jan. de 2024, 12:05",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Drew Cano",
    email: "drew.cano@internal.tools",
    role: "Convidado",
    status: "Ativo",
    team: "Ferramentas Internas",
    workspace: ["Ferramentas Internas"],
    joinedDate: "21 de jul. de 2023, 20:40",
    lastActive: 3 * 60,
  },
  {
    name: "Orlando Diggs",
    email: "orlando.diggs@acme.inc",
    role: "Somente Leitura",
    status: "Desativado",
    team: "Receita",
    workspace: ["Acme Inc."],
    joinedDate: "16 de set. de 2023, 15:25",
    lastActive: 6,
  },
  {
    name: "Andi Lane",
    email: "andi.lane@weblabs.studio",
    role: "Colaborador",
    status: "Ativo",
    team: "Operações de Pessoal",
    workspace: ["Weblabs Studio", "Sandbox"],
    joinedDate: "04 de nov. de 2022, 9:50",
    lastActive: 12,
  },
  {
    name: "Kate Morrison",
    email: "kate.morrison@weblabs.studio",
    role: "Administrador",
    status: "Ativo",
    team: "Plataforma",
    workspace: ["Weblabs Studio"],
    joinedDate: "30 de dez. de 2023, 16:35",
    lastActive: 30,
  },
  {
    name: "Alec Whitten",
    email: "alec.whitten@internal.tools",
    role: "Líder de Equipe",
    status: "Suspenso",
    team: "Ferramentas Internas",
    workspace: ["Ferramentas Internas"],
    joinedDate: "12 de fev. de 2024, 10:20",
    lastActive: 8 * 24 * 60,
  },
  {
    name: "Ariana Decker",
    email: "ariana.decker@weblabs.studio",
    role: "Colaborador",
    status: "Ativo",
    team: "Crescimento",
    workspace: ["Weblabs Studio"],
    joinedDate: "08 de ago. de 2023, 13:10",
    lastActive: 24 * 60,
  },
  {
    name: "Steven Tey",
    email: "steven.tey@sandbox.dev",
    role: "Convidado",
    status: "Convite pendente",
    team: "Operações de Cliente",
    workspace: ["Sandbox"],
    joinedDate: "17 de jan. de 2024, 17:45",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Lori Bryson",
    email: "lori.bryson@acme.inc",
    role: "Administrador de Cobrança",
    status: "Ativo",
    team: "Financeiro",
    workspace: ["Acme Inc."],
    joinedDate: "02 de out. de 2023, 11:15",
    lastActive: 45,
  },
  {
    name: "Koray Okumus",
    email: "koray.okumus@weblabs.studio",
    role: "Administrador de Segurança",
    status: "Ativo",
    team: "Ferramentas Internas",
    workspace: ["Weblabs Studio", "Ferramentas Internas"],
    joinedDate: "22 de mai. de 2024, 8:30",
    lastActive: 10,
  },
  {
    name: "Josh Miller",
    email: "josh.miller@internal.tools",
    role: "Somente Leitura",
    status: "Ativo",
    team: "Conformidade",
    workspace: ["Ferramentas Internas"],
    joinedDate: "14 de jul. de 2023, 18:05",
    lastActive: 4 * 60,
  },
  {
    name: "Mollie Hall",
    email: "mollie.hall@weblabs.studio",
    role: "Colaborador",
    status: "Desativado",
    team: "Plataforma",
    workspace: ["Weblabs Studio"],
    joinedDate: "26 de nov. de 2022, 15:40",
    lastActive: 21 * 24 * 60,
  },
  {
    name: "Rene Wells",
    email: "rene.wells@acme.inc",
    role: "Líder de Equipe",
    status: "Ativo",
    team: "Receita",
    workspace: ["Acme Inc."],
    joinedDate: "11 de abr. de 2024, 9:05",
    lastActive: 18,
  },
  {
    name: "Rylee Howard",
    email: "rylee.howard@sandbox.dev",
    role: "Convidado",
    status: "Bloqueado",
    team: "Crescimento",
    workspace: ["Sandbox"],
    joinedDate: "09 de set. de 2023, 12:25",
    lastActive: 2 * 24 * 60,
  },
  {
    name: "Sienna Hewitt",
    email: "sienna.hewitt@weblabs.studio",
    role: "Administrador",
    status: "Ativo",
    team: "Ferramentas Internas",
    workspace: ["Weblabs Studio", "Ferramentas Internas"],
    joinedDate: "05 de dez. de 2023, 14:15",
    lastActive: 0,
  },
  {
    name: "Noah Pierre",
    email: "noah.pierre@weblabs.studio",
    role: "Colaborador",
    status: "Ativo",
    team: "Plataforma",
    workspace: ["Weblabs Studio"],
    joinedDate: "18 de jun. de 2024, 16:50",
    lastActive: 7,
  },
  {
    name: "Eve Lechner",
    email: "eve.lechner@acme.inc",
    role: "Somente Leitura",
    status: "Suspenso",
    team: "Financeiro",
    workspace: ["Acme Inc."],
    joinedDate: "01 de mar. de 2023, 10:10",
    lastActive: 30 * 24 * 60,
  },
  {
    name: "Zahir McClure",
    email: "zahir.mcclure@internal.tools",
    role: "Administrador de Segurança",
    status: "Ativo",
    team: "Ferramentas Internas",
    workspace: ["Ferramentas Internas"],
    joinedDate: "07 de fev. de 2024, 19:20",
    lastActive: 60,
  },
  {
    name: "Mia Romberg",
    email: "mia.romberg@weblabs.studio",
    role: "Administrador de Cobrança",
    status: "Convite pendente",
    team: "Financeiro",
    workspace: ["Weblabs Studio"],
    joinedDate: "29 de abr. de 2024, 11:55",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Nico Arendt",
    email: "nico.arendt@sandbox.dev",
    role: "Colaborador",
    status: "Ativo",
    team: "Operações de Cliente",
    workspace: ["Sandbox", "Ferramentas Internas"],
    joinedDate: "13 de mai. de 2024, 18:35",
    lastActive: 25,
  },
];

export const filters = {
  role: [
    "Todos",
    "Proprietário do Espaço de Trabalho",
    "Administrador",
    "Administrador de Cobrança",
    "Administrador de Segurança",
    "Líder de Equipe",
    "Colaborador",
    "Convidado",
    "Somente Leitura",
  ],
  team: ["Todos", ...teamValues],
  status: ["Todos", "Ativo", "Convite pendente", "Desativado", "Bloqueado", "Suspenso"],
  workspace: ["Todos", "Weblabs Studio", "Sandbox", "Ferramentas Internas", "Acme Inc."],
};

export const statusMeta: Record<UserStatus, { badgeClass: string; dotClass: string }> = {
  Ativo: {
    badgeClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    dotClass: "bg-emerald-500",
  },
  "Convite pendente": {
    badgeClass: "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400",
    dotClass: "bg-amber-500",
  },
  Desativado: {
    badgeClass: "border-border bg-muted/50 text-muted-foreground",
    dotClass: "bg-muted-foreground",
  },
  Bloqueado: {
    badgeClass: "border-destructive/20 bg-destructive/10 text-destructive",
    dotClass: "bg-destructive",
  },
  Suspenso: {
    badgeClass: "border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    dotClass: "bg-orange-500",
  },
};
