name: No Response

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction/close-response@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Closing this issue because it has not had any activity since being labeled
            `needs-more-info`. Feel free to reopen if this is still relevant.
          close-issue-label: "closed-by-bot"
